// @generated
// This file is @generated by prost-build.
/// Generic error server can send (edge-safe).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ErrorEvent {
    #[prost(string, tag="1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
/// Example extra query result types (add your own as needed)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSessionStateQuery {
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionStateReply {
    #[prost(message, optional, tag="1")]
    pub session: ::core::option::Option<super::super::super::game::session::v1::GameSession>,
    /// example for puzzle
    #[prost(int32, repeated, tag="2")]
    pub board: ::prost::alloc::vec::Vec<i32>,
    /// optimistic locking / projection version
    #[prost(uint64, tag="3")]
    pub version: u64,
}
/// Start-session command (already in your schema)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartGameSessionCommand {
    #[prost(enumeration="super::super::super::game::types::v1::GameType", tag="1")]
    pub game_type: i32,
    #[prost(message, repeated, tag="2")]
    pub player_ids: ::prost::alloc::vec::Vec<super::super::super::game::types::v1::PlayerId>,
    #[prost(oneof="start_game_session_command::Config", tags="10, 11, 12")]
    pub config: ::core::option::Option<start_game_session_command::Config>,
}
/// Nested message and enum types in `StartGameSessionCommand`.
pub mod start_game_session_command {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Config {
        #[prost(message, tag="10")]
        Trivia(super::super::super::super::game::trivia::v1::TriviaRules),
        #[prost(message, tag="11")]
        Puzzle(super::super::super::super::game::puzzle::v1::PuzzleRules),
        #[prost(string, tag="12")]
        RulesetId(::prost::alloc::string::String),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameSessionStartedEvent {
    #[prost(message, optional, tag="1")]
    pub session: ::core::option::Option<super::super::super::game::session::v1::GameSession>,
}
/// Top-level envelope
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Envelope {
    /// Client sets this; server echoes it in Reply or ErrorEvent.
    #[prost(string, tag="100")]
    pub correlation_id: ::prost::alloc::string::String,
    #[prost(oneof="envelope::Body", tags="1, 2, 3, 4, 199")]
    pub body: ::core::option::Option<envelope::Body>,
}
/// Nested message and enum types in `Envelope`.
pub mod envelope {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        /// client -> server (writes)
        #[prost(message, tag="1")]
        Command(super::Command),
        /// client -> server (reads)
        #[prost(message, tag="2")]
        Query(super::Query),
        /// server -> client (answers to Query/Command)
        #[prost(message, tag="3")]
        Reply(super::Reply),
        /// server -> client (push)
        #[prost(message, tag="4")]
        Event(super::Event),
        /// server -> client (edge-safe error)
        #[prost(message, tag="199")]
        Error(super::ErrorEvent),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Command {
    #[prost(oneof="command::Kind", tags="1, 2, 3, 10, 11")]
    pub kind: ::core::option::Option<command::Kind>,
}
/// Nested message and enum types in `Command`.
pub mod command {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag="1")]
        StartGameSession(super::StartGameSessionCommand),
        #[prost(message, tag="2")]
        TriviaSubmitAnswer(super::super::super::super::game::trivia::v1::SubmitAnswerCommand),
        #[prost(message, tag="3")]
        TriviaRevealHint(super::super::super::super::game::trivia::v1::RevealHintCommand),
        #[prost(message, tag="10")]
        PuzzleMovePiece(super::super::super::super::game::puzzle::v1::MovePieceCommand),
        #[prost(message, tag="11")]
        PuzzleUndoMove(super::super::super::super::game::puzzle::v1::UndoMoveCommand),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Query {
    #[prost(oneof="query::Kind", tags="1")]
    pub kind: ::core::option::Option<query::Kind>,
}
/// Nested message and enum types in `Query`.
pub mod query {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        /// add more queries here later…
        #[prost(message, tag="1")]
        GetSessionState(super::GetSessionStateQuery),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Reply {
    #[prost(oneof="reply::Kind", tags="101, 102, 103, 110, 111, 201")]
    pub kind: ::core::option::Option<reply::Kind>,
}
/// Nested message and enum types in `Reply`.
pub mod reply {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        /// Command acks
        #[prost(message, tag="101")]
        GameSessionStarted(super::GameSessionStartedEvent),
        #[prost(message, tag="102")]
        TriviaAnswerAccepted(super::super::super::super::game::trivia::v1::AnswerAcceptedEvent),
        #[prost(message, tag="103")]
        TriviaHintRevealed(super::super::super::super::game::trivia::v1::HintRevealedEvent),
        #[prost(message, tag="110")]
        PuzzlePieceMoved(super::super::super::super::game::puzzle::v1::PieceMovedEvent),
        #[prost(message, tag="111")]
        PuzzleMoveUndone(super::super::super::super::game::puzzle::v1::MoveUndoneEvent),
        /// Query replies
        #[prost(message, tag="201")]
        SessionState(super::SessionStateReply),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    #[prost(oneof="event::Kind", tags="110")]
    pub kind: ::core::option::Option<event::Kind>,
}
/// Nested message and enum types in `Event`.
pub mod event {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        /// server-push updates, separate from direct replies
        ///
        /// Add presence/clock/announcements etc. here…
        #[prost(message, tag="110")]
        PuzzlePieceMoved(super::super::super::super::game::puzzle::v1::PieceMovedEvent),
    }
}
// @@protoc_insertion_point(module)
