// @generated
// This file is @generated by prost-build.
/// IDs
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameSessionId {
    #[prost(string, tag="1")]
    pub value: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerId {
    #[prost(string, tag="1")]
    pub value: ::prost::alloc::string::String,
}
/// Optional audit helper (use when you need it)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Audit {
    /// 
    #[prost(int32, tag="1")]
    pub dummy_slot: i32,
    #[prost(message, optional, tag="2")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="3")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Enums
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GameType {
    Unspecified = 0,
    Trivia = 1,
    Puzzle = 2,
}
impl GameType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            GameType::Unspecified => "GAME_TYPE_UNSPECIFIED",
            GameType::Trivia => "GAME_TYPE_TRIVIA",
            GameType::Puzzle => "GAME_TYPE_PUZZLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GAME_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "GAME_TYPE_TRIVIA" => Some(Self::Trivia),
            "GAME_TYPE_PUZZLE" => Some(Self::Puzzle),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SessionStatus {
    Unspecified = 0,
    Created = 1,
    Active = 2,
    Ended = 3,
    Cancelled = 4,
}
impl SessionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            SessionStatus::Unspecified => "SESSION_STATUS_UNSPECIFIED",
            SessionStatus::Created => "SESSION_STATUS_CREATED",
            SessionStatus::Active => "SESSION_STATUS_ACTIVE",
            SessionStatus::Ended => "SESSION_STATUS_ENDED",
            SessionStatus::Cancelled => "SESSION_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SESSION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "SESSION_STATUS_CREATED" => Some(Self::Created),
            "SESSION_STATUS_ACTIVE" => Some(Self::Active),
            "SESSION_STATUS_ENDED" => Some(Self::Ended),
            "SESSION_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
