// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartUserSessionCommand {
    #[prost(string, tag="1")]
    pub client_version: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionStartedEvent {
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Envelope {
    #[prost(string, tag="100")]
    pub correlation_id: ::prost::alloc::string::String,
    #[prost(oneof="envelope::Msg", tags="1, 2")]
    pub msg: ::core::option::Option<envelope::Msg>,
}
/// Nested message and enum types in `Envelope`.
pub mod envelope {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag="1")]
        StartUserSessionCommand(super::StartUserSessionCommand),
        #[prost(message, tag="2")]
        SessionStartedEvent(super::SessionStartedEvent),
    }
}
// @@protoc_insertion_point(module)
