// @generated
// This file is @generated by prost-build.
// NOTE: GameType/Ids now come from types.v1

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameSession {
    #[prost(message, optional, tag="1")]
    pub id: ::core::option::Option<super::super::types::v1::GameSessionId>,
    #[prost(enumeration="super::super::types::v1::GameType", tag="2")]
    pub game_type: i32,
    #[prost(message, repeated, tag="3")]
    pub player_ids: ::prost::alloc::vec::Vec<super::super::types::v1::PlayerId>,
    #[prost(enumeration="super::super::types::v1::SessionStatus", tag="4")]
    pub status: i32,
    #[prost(message, optional, tag="5")]
    pub created_at: ::core::option::Option<super::super::super::super::super::google::protobuf::Timestamp>,
    /// optional external reference
    #[prost(string, tag="6")]
    pub ruleset_id: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGameSessionRequest {
    #[prost(enumeration="super::super::types::v1::GameType", tag="1")]
    pub game_type: i32,
    #[prost(message, repeated, tag="2")]
    pub player_ids: ::prost::alloc::vec::Vec<super::super::types::v1::PlayerId>,
    #[prost(oneof="create_game_session_request::Config", tags="10, 11, 12")]
    pub config: ::core::option::Option<create_game_session_request::Config>,
}
/// Nested message and enum types in `CreateGameSessionRequest`.
pub mod create_game_session_request {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Config {
        #[prost(message, tag="10")]
        Trivia(super::super::super::trivia::v1::TriviaRules),
        #[prost(message, tag="11")]
        Puzzle(super::super::super::puzzle::v1::PuzzleRules),
        #[prost(string, tag="12")]
        RulesetId(::prost::alloc::string::String),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGameSessionResponse {
    #[prost(message, optional, tag="1")]
    pub session: ::core::option::Option<GameSession>,
}
// @@protoc_insertion_point(module)
