// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TriviaRules {
    #[prost(uint32, tag="1")]
    pub num_questions: u32,
    #[prost(uint32, tag="2")]
    pub seconds_per_question: u32,
    #[prost(bool, tag="3")]
    pub negative_marking: bool,
    #[prost(enumeration="TriviaCategory", repeated, tag="4")]
    pub categories: ::prost::alloc::vec::Vec<i32>,
    #[prost(uint32, tag="5")]
    pub max_players: u32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TriviaCategory {
    Unspecified = 0,
    GeneralKnowledge = 1,
    Science = 2,
    History = 3,
}
impl TriviaCategory {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TriviaCategory::Unspecified => "TRIVIA_CATEGORY_UNSPECIFIED",
            TriviaCategory::GeneralKnowledge => "TRIVIA_CATEGORY_GENERAL_KNOWLEDGE",
            TriviaCategory::Science => "TRIVIA_CATEGORY_SCIENCE",
            TriviaCategory::History => "TRIVIA_CATEGORY_HISTORY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TRIVIA_CATEGORY_UNSPECIFIED" => Some(Self::Unspecified),
            "TRIVIA_CATEGORY_GENERAL_KNOWLEDGE" => Some(Self::GeneralKnowledge),
            "TRIVIA_CATEGORY_SCIENCE" => Some(Self::Science),
            "TRIVIA_CATEGORY_HISTORY" => Some(Self::History),
            _ => None,
        }
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubmitAnswerCommand {
    #[prost(message, optional, tag="1")]
    pub session_id: ::core::option::Option<super::super::types::v1::GameSessionId>,
    #[prost(message, optional, tag="2")]
    pub player_id: ::core::option::Option<super::super::types::v1::PlayerId>,
    #[prost(string, tag="3")]
    pub answer: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevealHintCommand {
    #[prost(message, optional, tag="1")]
    pub session_id: ::core::option::Option<super::super::types::v1::GameSessionId>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnswerAcceptedEvent {
    #[prost(message, optional, tag="1")]
    pub session_id: ::core::option::Option<super::super::types::v1::GameSessionId>,
    #[prost(message, optional, tag="2")]
    pub player_id: ::core::option::Option<super::super::types::v1::PlayerId>,
    #[prost(int32, tag="3")]
    pub delta_score: i32,
    #[prost(int32, tag="4")]
    pub total_score: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HintRevealedEvent {
    #[prost(message, optional, tag="1")]
    pub session_id: ::core::option::Option<super::super::types::v1::GameSessionId>,
    #[prost(string, tag="2")]
    pub hint_text: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
