// @generated
// This file is @generated by prost-build.
/// ClientEnvelope is the top-level message from the client over WebSocket.
/// The Rust code `ws/mod.rs` expects this structure.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientEnvelope {
    #[prost(oneof="client_envelope::Message", tags="1, 2")]
    pub message: ::core::option::Option<client_envelope::Message>,
}
/// Nested message and enum types in `ClientEnvelope`.
pub mod client_envelope {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag="1")]
        StartGame(super::StartGameCommand),
        #[prost(message, tag="2")]
        GameCommand(super::GameCommandEnvelope),
    }
}
/// Sent by the client to initiate a game session.
/// The Rust code `ws/mod.rs` expects this to have a `game_type` field.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StartGameCommand {
    #[prost(enumeration="super::super::super::game::types::v1::GameType", tag="1")]
    pub game_type: i32,
}
/// GameCommandEnvelope wraps all in-game actions.
/// The Rust code `ws/mod.rs` expects this structure.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameCommandEnvelope {
    #[prost(oneof="game_command_envelope::Command", tags="1, 2, 3, 4")]
    pub command: ::core::option::Option<game_command_envelope::Command>,
}
/// Nested message and enum types in `GameCommandEnvelope`.
pub mod game_command_envelope {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Command {
        #[prost(message, tag="1")]
        PuzzleMove(super::super::super::super::game::puzzle::v1::MovePieceCommand),
        #[prost(message, tag="2")]
        PuzzleUndo(super::super::super::super::game::puzzle::v1::UndoMoveCommand),
        #[prost(message, tag="3")]
        TriviaSubmit(super::super::super::super::game::trivia::v1::SubmitAnswerCommand),
        #[prost(message, tag="4")]
        TriviaHint(super::super::super::super::game::trivia::v1::RevealHintCommand),
    }
}
/// ServerEnvelope is the top-level message from the server to the client.
/// Your Rust code will need this to send events and status updates back.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerEnvelope {
    #[prost(oneof="server_envelope::Message", tags="1, 2, 3, 4")]
    pub message: ::core::option::Option<server_envelope::Message>,
}
/// Nested message and enum types in `ServerEnvelope`.
pub mod server_envelope {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        /// e.g., "AUTH_SUCCESS", "AUTH_FAILED"
        #[prost(string, tag="1")]
        AuthStatus(::prost::alloc::string::String),
        /// e.g., A JSON string of the full game state
        #[prost(string, tag="2")]
        GameState(::prost::alloc::string::String),
        /// e.g., "Session not found"
        #[prost(string, tag="3")]
        Error(::prost::alloc::string::String),
        /// e.g., A specific game event
        #[prost(message, tag="4")]
        GameEvent(super::GameEventEnvelope),
    }
}
/// GameEventEnvelope wraps all game-specific events.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GameEventEnvelope {
    #[prost(oneof="game_event_envelope::Event", tags="1, 2")]
    pub event: ::core::option::Option<game_event_envelope::Event>,
}
/// Nested message and enum types in `GameEventEnvelope`.
pub mod game_event_envelope {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        /// Placeholder for puzzle events
        #[prost(string, tag="1")]
        PuzzleEvent(::prost::alloc::string::String),
        /// Placeholder for trivia events
        #[prost(string, tag="2")]
        TriviaEvent(::prost::alloc::string::String),
    }
}
// @@protoc_insertion_point(module)
